[platformio]
src_dir = PostureGuard_Arm
build_dir = build_output

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_port = COM13
monitor_port = COM13
extra_scripts = pre:set_temp.py
lib_extra_dirs = C:/rishabh/RKDM/.pio/libdeps/uno
